name: Build Game APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          if [ -d "block_puzzle" ]; then cd block_puzzle; fi
          flutter pub get

      - name: Build APK
        run: |
          if [ -d "block_puzzle" ]; then cd block_puzzle; fi
          flutter build apk --release

      - name: Save APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            **/build/app/outputs/flutter-apk/*.apk
